# Generated by Django 3.0.5 on 2020-04-02 14:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=datetime.datetime(2020, 4, 2, 14, 41, 56, 840232, tzinfo=utc))),
                ('updated_time', models.DateTimeField(default=datetime.datetime(2020, 4, 2, 14, 41, 56, 840262, tzinfo=utc))),
                ('code', models.CharField(max_length=10)),
                ('factory', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=200)),
            ],
        ),
    ]
